import React from 'react';

export default function CanvasView({ canvasData }) {
  // Datos de prueba (Fallback) en caso de que la API tarde en cargar
    const datos = canvasData || {
        propuesta_valor: "Cargando tu propuesta...",
            segmentos_cliente: "Analizando tu mercado...",
                canales: "Evaluando medios...",
                    relacion_clientes: "Procesando fidelización...",
                        fuentes_ingresos: "Calculando monetización...",
                            recursos_clave: "Identificando activos...",
                                actividades_clave: "Estructurando operaciones...",
                                    asociaciones_clave: "Mapeando aliados...",
                                        estructura_costos: "Calculando egresos...",
                                            base_minima_venta: 0
                                              };

                                                return (
                                                    <div className="max-w-7xl mx-auto p-4 md:p-8 bg-gray-50 min-h-screen">
                                                          
                                                                {/* Encabezado del Entregable */}
                                                                      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 border-b pb-4 border-gray-200">
                                                                              <div>
                                                                                        <h1 className="text-3xl font-black text-gray-900 tracking-tight">Tu Modelo de Negocio Automatizado</h1>
                                                                                                  <p className="text-gray-500 mt-1">Metodología: Querer, Poder y Saber Emprender</p>
                                                                                                          </div>
                                                                                                                  
                                                                                                                          {/* Métrica Financiera Clave */}
                                                                                                                                  <div className="mt-4 md:mt-0 p-4 bg-emerald-50 border border-emerald-200 rounded-xl text-right">
                                                                                                                                            <span className="text-xs font-bold text-emerald-700 uppercase tracking-wider block">Base Mínima de Venta (Mensual)</span>
                                                                                                                                                      <span className="text-2xl font-black text-emerald-900">
                                                                                                                                                                  ${datos.base_minima_venta.toLocaleString('es-MX')} <span className="text-sm font-normal text-emerald-700">MXN</span>
                                                                                                                                                                            </span>
                                                                                                                                                                                    </div>
                                                                                                                                                                                          </div>

                                                                                                                                                                                                {/* El Lienzo Canvas (Grid de 5 Columnas) */}
                                                                                                                                                                                                      <div className="grid grid-cols-1 md:grid-cols-5 gap-4 mb-6">
                                                                                                                                                                                                              
                                                                                                                                                                                                                      {/* 1. Alianzas Clave */}
                                                                                                                                                                                                                              <div className="md:col-span-1 bg-white p-5 rounded-xl shadow-sm border border-gray-100 flex flex-col justify-between min-h-[220px]">
                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                    <h3 className="text-xs font-bold text-indigo-600 uppercase tracking-wider mb-2">🤝 Alianzas Clave</h3>
                                                                                                                                                                                                                                                                <p className="text-sm text-gray-700 leading-relaxed">{datos.asociaciones_clave}</p>
                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                          {/* Bloque Central Doble (Actividades y Recursos) */}
                                                                                                                                                                                                                                                                                                  <div className="md:col-span-1 flex flex-col gap-4">
                                                                                                                                                                                                                                                                                                            {/* 2. Actividades Clave */}
                                                                                                                                                                                                                                                                                                                      <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100 flex-1">
                                                                                                                                                                                                                                                                                                                                  <h3 className="text-xs font-bold text-indigo-600 uppercase tracking-wider mb-2">⚡ Actividades Clave</h3>
                                                                                                                                                                                                                                                                                                                                              <p className="text-sm text-gray-700 leading-relaxed">{datos.actividades_clave}</p>
                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                  {/* 3. Recursos Clave */}
                                                                                                                                                                                                                                                                                                                                                                            <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100 flex-1">
                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="text-xs font-bold text-indigo-600 uppercase tracking-wider mb-2">🧱 Recursos Clave</h3>
                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-sm text-gray-700 leading-relaxed">{datos.recursos_clave}</p>
                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                              {/* 4. Propuesta de Valor (El Centro del Lienzo) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="md:col-span-1 bg-indigo-900 p-5 rounded-xl shadow-md border border-indigo-950 flex flex-col justify-between text-white min-h-[460px] md:row-span-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 className="text-xs font-bold text-indigo-300 uppercase tracking-wider mb-2">💎 Propuesta de Valor</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-sm font-medium leading-relaxed text-indigo-50">{datos.propuesta_valor}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mt-4 pt-4 border-t border-indigo-800 text-xs text-indigo-200 italic">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        *Validada bajo el Pentágono del Descubrimiento.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Bloque Central Derecho (Relación y Canales) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="md:col-span-1 flex flex-col gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* 5. Relación con Clientes */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100 flex-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="text-xs font-bold text-indigo-600 uppercase tracking-wider mb-2">❤️ Relación con Clientes</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-sm text-gray-700 leading-relaxed">{datos.relacion_clientes}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* 6. Canales de Distribución */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100 flex-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3 className="text-xs font-bold text-indigo-600 uppercase tracking-wider mb-2">🚀 Canales</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-sm text-gray-700 leading-relaxed">{datos.canales}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* 7. Segmentos de Cliente */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="md:col-span-1 bg-white p-5 rounded-xl shadow-sm border border-gray-100 flex flex-col justify-between min-h-[220px]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 className="text-xs font-bold text-indigo-600 uppercase tracking-wider mb-2">🎯 Segmentos de Cliente</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-sm text-gray-700 leading-relaxed">{datos.segmentos_cliente}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Base del Lienzo (Estructura Financiera en 2 Columnas) */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* 8. Estructura de Costos */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3 className="text-xs font-bold text-rose-600 uppercase tracking-wider mb-2">📉 Estructura de Costos</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-sm text-gray-700 leading-relaxed">{datos.estructura_costos}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* 9. Fuentes de Ingresos */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="text-xs font-bold text-emerald-600 uppercase tracking-wider mb-2">📈 Flujos de Ingresos</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-sm text-gray-700 leading-relaxed">{datos.fuentes_ingresos}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        