import OpenAI from 'openai';

// 1. Inicializamos el cliente de DeepSeek de forma global
const deepseek = new OpenAI({
  apiKey: null, // Se asignará dinámicamente dentro de la petición desde las variables de entorno
    baseURL: "https://api.deepseek.com"
    });

    export async function onRequestPost(context) {
      try {
          // Extraemos las llaves secretas configuradas en Cloudflare / .env.local
              const DEEPSEEK_KEY = context.env.DEEPSEEK_API_KEY;
                  const MONGO_API_KEY = context.env.MONGODB_DATA_API_KEY;
                      const MONGO_APP_ID = context.env.MONGODB_APP_ID; // Tu App ID de Atlas Data API

                          deepseek.apiKey = DEEPSEEK_KEY;

                              // 2. Recibir los datos desde tu componente Wizard.jsx
                                  const { narrativa, usuarioId, diagnosticoId } = await context.request.json();

                                      // 3. Llamada analítica a DeepSeek con razonamiento profundo (Thinking Mode)
                                          const aiResponse = await deepseek.chat.completions.create({
                                                model: "deepseek-v4-pro",
                                                      response_format: { type: "json_object" },
                                                            messages: [
                                                                    {
                                                                              role: "system",
                                                                                        content: `Eres el consultor analítico del libro 'Querer, Poder y Saber Emprender'. 
                                                                                                  Analiza la narrativa del usuario para extraer la 'Foto Rápida'.
                                                                                                            Devuelve OBLIGATORIAMENTE un JSON con esta estructura exacta:
                                                                                                                      {
                                                                                                                                  "sector_mercado": "string",
                                                                                                                                              "modelo_monetizacion": "B2C/B2B",
                                                                                                                                                          "registro_ingresos": "Si/No/Informal",
                                                                                                                                                                      "registro_gastos": "Si/No/Informal",
                                                                                                                                                                                  "percepcion_ganancia": 1-4,
                                                                                                                                                                                              "dolores_prioritarios": ["dolor1", "dolor2"],
                                                                                                                                                                                                          "intervencion_socratica": "pregunta para profundizar o vacío"
                                                                                                                                                                                                                    }`
                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                    { role: "user", content: narrativa }
                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                reasoning_effort: "high",
                                                                                                                                                                                                                                                      extra_body: { thinking: { type: "enabled" } }
                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                              // Parseamos el JSON que nos devolvió DeepSeek
                                                                                                                                                                                                                                                                  const analisisIA = JSON.parse(aiResponse.choices[0].message.content);

                                                                                                                                                                                                                                                                      // 4. Guardar el resultado en MongoDB Atlas usando la Data API HTTP
                                                                                                                                                                                                                                                                          const urlMongo = `https://data.mongodb-api.com/app/${MONGO_APP_ID}/endpoint/data/v1/action/updateOne`;
                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                  const mongoPayload = {
                                                                                                                                                                                                                                                                                        dataSource: "Cluster0", // Nombre de tu clúster en Atlas
                                                                                                                                                                                                                                                                                              database: "gokulab_platform", // Tu base de datos
                                                                                                                                                                                                                                                                                                    collection: "diagnosticos",   // Tu colección de la Fase 3
                                                                                                                                                                                                                                                                                                          filter: { _id: { $oid: diagnosticoId } },
                                                                                                                                                                                                                                                                                                                update: {
                                                                                                                                                                                                                                                                                                                        $set: {
                                                                                                                                                                                                                                                                                                                                  "estado_progreso": "bloque_1_completado",
                                                                                                                                                                                                                                                                                                                                            "bloque_1_foto_rapida": {
                                                                                                                                                                                                                                                                                                                                                        "narrativa_usuario": narrativa,
                                                                                                                                                                                                                                                                                                                                                                    "analisis_ia": analisisIA
                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                        "ultima_actualizacion": new Date().toISOString()
                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                              const mongoResponse = await fetch(urlMongo, {
                                                                                                                                                                                                                                                                                                                                                                                                                    method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                                                          headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                  "Content-Type": "application/json",
                                                                                                                                                                                                                                                                                                                                                                                                                                          "Access-Control-Request-Headers": "*",
                                                                                                                                                                                                                                                                                                                                                                                                                                                  "api-key": MONGO_API_KEY
                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                              body: JSON.stringify(mongoPayload)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!mongoResponse.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            throw new Error("Error al escribir en MongoDB Atlas");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // 5. Devolvemos el análisis de la IA al frontend para que el Wizard actúe
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return new Response(JSON.stringify(analisisIA), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              headers: { "Content-Type": "application/json" }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return new Response(JSON.stringify({ error: error.message }), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              status: 500,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    headers: { "Content-Type": "application/json" }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          